//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBCaseSystem_KokovinMedvedevStartsev
{
    using System;
    using System.Collections.Generic;
    
    public partial class QueryObject
    {
        public int Id { get; set; }
        public string ObjectID { get; set; }
        public QueryObjectType Type { get; set; }
    
        public virtual Query Query { get; set; }
    }
}
